### ISSUE TITLE
Read symbols from #include files..?

### ISSUE THREAD

**Issue by erohtar** [mark-wiemer/vscode-autohotkey-plus-plus#121] opened 2022-06-02 13:52 UTC
Hi @mark-wiemer, Extremely helpful extension - brilliant!
I've been a long time SciTE user for .ahk and one thing I love about working with it there is TillaGoto (utility that SciTE4AutoHotkey comes with) can find and go to functions defined in #include files.
I've tried everything but wasn't able to have VSCode find/goto a function defined in an #include file - did I miss anything or is that not supported at all? If so, any chance you'd consider adding it?

Again, love your extension!

**Comment by erohtar** [comment] 2022-06-02 14:54
@fade2gray, Good to know someone else felt the need for it too. Though it's disheartening to see it's been over an year to that request and it wasn't added... hopefully that changes soon.

**Comment by mark-wiemer** [comment] 2022-06-02 15:35
Congrats, this is officially the straw that broke my back and cemented my decision to return to supporting this project. See #21 for more info :)

**Comment by erohtar** [comment] 2022-06-02 15:42
Wow! In that case, I'm really glad I dropped a heavy enough straw lol
Really looking forward to future updates (I'll admit, the one I requested is the most important to me right now).

> See #21 for more info :)
* make it 50 stars!

**Comment by mark-wiemer** [comment] 2022-06-03 01:54
As my first act on the codebase, I'm closing this as a duplicate of #44

**Closed by mark-wiemer** 2022-06-03 01:54 UTC
Labels: duplicate, enhancement
