### ISSUE TITLE
Extension hangs and prevents other extensions from running

### ISSUE THREAD

**Issue by RaptorX** [mark-wiemer/vscode-autohotkey-plus-plus#203] opened 2022-07-31 16:35 UTC
## Description

I have been noticing that the Intellisense feature has been very spotty after installing the new pre-release version of ahk++.
This issue is happening even with the stable release version.

Sometimes I get no suggestions, even when I press `Ctrl+Space`. Restarting Code.exe not always helps.
I have found that switching to another lexer like HTML or CSV **sometimes** fixes the issue.

## Reproduction steps

Even though this might happen at random times it usually happens when I start vscode with a new `ahk` file open.

## Expected behavior

No error should occur.

## Additional context

This bug might be related to #65 

I have noticed that sometimes I get the following notification with the newest version of ahk++:
![image](https://user-images.githubusercontent.com/328761/182035118-12d48c4a-2cae-45da-8e5c-4551ccd7e26f.png)

After some troubleshooting I found that we can see the extension as unresponsive:
![image](https://user-images.githubusercontent.com/328761/182035275-1a6684a1-4cc5-4468-b74e-dc7281f41df9.png)

And some valuable information can be seen in the window log:
```
[2022-07-31 11:43:25.841] [renderer1] [warning] {}
[2022-07-31 11:52:23.769] [renderer1] [info] UNRESPONSIVE extension host: starting to profile NOW
[2022-07-31 11:52:28.855] [renderer1] [warning] UNRESPONSIVE extension host: 'mark-wiemer.vscode-autohotkey-plus-plus' took 99% of 6544.599ms, saved PROFILE here: 'file:///c%3A/Users/RaptorX/AppData/Local/Temp/exthost-e537b6.cpuprofile' [{"id":"gc","total":77637,"percentage":1},{"id":"mark-wiemer.vscode-autohotkey-plus-plus","total":6465380,"percentage":99},{"id":"program","total":149,"percentage":0},{"id":"self","total":1233,"percentage":0}]
```

Here you can find the file in question:
[exthost-e537b6.zip](https://github.com/mark-wiemer/vscode-autohotkey-plus-plus/files/9229263/exthost-e537b6.zip)

This can happen multiple times in a session.

**Comment by mark-wiemer** [comment] 2022-07-31 17:57
Thanks for reporting this. I'll definitely fix this before we move to the stable release :)

**Comment by mark-wiemer** [comment] 2022-09-17 02:21
Hey @RaptorX , are you by chance working on a large repo that you can share with me? I'm seeing the issue is with this line of code:

https://github.com/mark-wiemer/vscode-autohotkey-plus-plus/blob/1cdf6c46f1cee178eaf1442cb5be293985bd1e24/src/parser/parser.ts#L19

It reads all files in the build directory, so if it's a large directory it could take a while. I'm not able to reproduce the issue on the projects I have :/

**Comment by mark-wiemer** [comment] 2022-09-17 02:23
Additionally, this logic shouldn't have changed much since 2.8.4. Can you confirm you're only seeing this issue with 2.8.5?

**Comment by RaptorX** [comment] 2022-09-17 16:04
Most of my repos are not that large, that's the reason I was surprised by this.
I will have to try again since I updated VSCode and I havent experienced any other similar issues.

I will give it some testing and let you know.

**Comment by mark-wiemer** [comment] 2022-09-25 05:28
Hey @RaptorX, I'm curious if you're having this issue with the latest version of AutoHotkey Plus as well. Knowing how frequently it happens would help me prioritize. I initially thought this would be an easy task to debug but of course it's never as simple as it seems :( I still haven't been able to repro the issue.

**Comment by RaptorX** [comment] 2022-09-26 13:07
This issue is extremely intermittent. It is not happening recently, but just comes back from time to time

But maybe it is related to another extension.

https://github.com/zero-plusplus/vscode-autohotkey-debug/issues/242#issuecomment-1257525647

In that other thread we are discussing an unrelated issue, but the only common thing that Thomas Khan and I have in common is that we both have the same extensions for autohotkey.

I am using [Autohotkey v2 Language Support](https://github.com/thqby/vscode-autohotkey2-lsp) and [Autohotkey Debug](https://github.com/zero-plusplus/vscode-autohotkey-debug) beside your script.

So there might be some overlapping functions going on.

**Comment by mark-wiemer** [comment] 2022-09-30 06:47
OK, that's good to know. I think we're going to go ahead and release without addressing this bug, as I'm still unable to reproduce it. Plus, it looks like when it does happen, restarting VS Code is able to mitigate the issue?

**Comment by RaptorX** [comment] 2022-09-30 12:59
> OK, that's good to know. I think we're going to go ahead and release without addressing this bug, as I'm still unable to reproduce it. Plus, it looks like when it does happen, restarting VS Code is able to mitigate the issue?

When it was happening, no. Restarting VSCode didnt fix the issue. Thats the reason why I suspect is more of a conflict with another extension more than anything and I really suspect is the Autohotkey V2 language support one.

**Comment by mark-wiemer** [comment] 2022-10-01 17:25
OK, thanks for the update. Let me look into this one a bit further. If you're ever able to repro, I'd greatly appreciate if you could post the list of active extensions and the folder you were trying to open. Additionally, once you repro, you could try disabling other extensions to see if they might be the cause. There is a great [extension bisect](https://code.visualstudio.com/blogs/2021/02/16/extension-bisect) built in to VS Code that you can try to isolate the problem.

For now, I'm going to close this as "cannot reproduce", but I'm happy to re-open if you're able to provide additional details. Just @mark-wiemer so I'll be sure to see it :)

**Closed** 2022-10-02 01:54 UTC
Labels: bug, prerelease
