### ISSUE TITLE
wrong formating after v := v2 ? v2 : ""

### ISSUE THREAD

**Issue by ggrigorov** [mark-wiemer/vscode-autohotkey-plus-plus#113] opened 2021-10-27 19:20 UTC
### Description

hello, there fellow developers, the issue that I have is to do with an extra spacing on "ret.settings ..." row. The worst of this is, that for some reason this bug affects functions below this code with a return order inside IF{} area.

### Unformatted input snippet

```autohotkey
testFn(s){
ret := {}
_s := "whatever"

ret.message := s.m ? s.m : ""
ret.settings := _s

return ret
}
```

### Expected formatted output snippet

```autohotkey
testFn(s){
    ret := {}
    _s := "whatever"

    ret.message := s.m ? s.m : ""
    ret.settings := _s

    return ret
}
```

### Actual formatted output snippet

```autohotkey
testFn(s){
    ret := {}
    _s := "whatever"

    ret.message := s.m ? s.m : ""
        ret.settings := _s

    return ret
}
```

### Additional context

Optionally, you may provide similar snippets with similar behavior.

**Comment by mark-wiemer** [comment] 2021-11-25 05:19
Closing as not able to reproduce. Yes I believe this issue was fixed in #32, please try to update to the latest version of the extension @ggrigorov :)

**Closed by mark-wiemer** 2021-11-25 05:19 UTC
Labels: bug, formatter
