### ISSUE TITLE
text cut-off 

### ISSUE THREAD

**Issue by Hungermanw3t** [mark-wiemer/vscode-autohotkey-plus-plus#114] opened 2021-11-25 07:32 UTC
while hovering over SendInput the they is cut off so i can't read the rest
![image](https://user-images.githubusercontent.com/90822602/143398582-578edabb-0fe8-4e29-b9c9-c2ad7b168176.png)

**Comment by fade2gray** [comment] 2021-11-25 14:13
May be hard to spot, but there is a horizontal scroll bar displayed in the quick info box when the text is too long.

![QuickInfoScrollBar](https://user-images.githubusercontent.com/1332009/143455486-514ea8be-1f6c-457d-8b2f-c67c847cd316.png)

Interestingly, though, the quick info for `Return` wraps at the hyphen in "...function-call...".

**Comment by mark-wiemer** [comment] 2021-11-25 23:55
Cannot reproduce, I am also seeing a horizontal scroll. Closing this is issue for now.

**Closed by mark-wiemer** 2021-11-25 23:55 UTC
